"""Improved description card component."""

from __future__ import annotations

import streamlit as st


def render_description_card(phase2: dict | None, had_description: bool) -> None:
    """Render the AI-improved description section.

    Parameters
    ----------
    phase2 : dict or None
        The phase2 response dict. If None or improved_description is None,
        renders a fallback message.
    had_description : bool
        Whether the user submitted a description in the input form.
    """
    st.markdown(
        'Improved Description <span class="ai-badge">Generated by AI</span>'
        if (phase2 is not None and phase2.get("improved_description"))
        else "Improved Description",
        unsafe_allow_html=True,
    )

    improved = None
    if phase2 is not None:
        improved = phase2.get("improved_description")

    if improved:
        st.markdown(
            f'<div style="'
            f"background:#f0fdf4;border-left:4px solid #22c55e;"
            f"padding:16px;border-radius:4px;margin-bottom:8px;"
            f'">'
            f"{improved}"
            f"</div>",
            unsafe_allow_html=True,
        )

        def _apply_description() -> None:
            st.session_state["form_description"] = st.session_state[
                "_pending_improved_description"
            ]
            st.session_state["_description_applied"] = True

        st.session_state["_pending_improved_description"] = improved

        st.button(
            "Use This Description",
            key="use_improved_description",
            help="Copy the AI-improved description into the input form.",
            on_click=_apply_description,
        )

        if st.session_state.pop("_description_applied", False):
            st.toast("Description updated in the input form.")

    elif had_description:
        st.info("AI description improvement unavailable.")
    else:
        st.info("Enter a description to receive AI improvement suggestions.")
