"""AI narrative explanation card component."""

from __future__ import annotations

import streamlit as st


def render_explanation_card(phase2: dict | None) -> None:
    """Render the AI explanation section.

    Parameters
    ----------
    phase2 : dict or None
        The phase2 response dict. If None or narrative_explanation is None,
        renders a fallback message.
    """
    explanation = None
    if phase2 is not None:
        explanation = phase2.get("narrative_explanation")

    st.markdown(
        'AI Explanation <span class="ai-badge">Generated by AI</span>'
        if explanation
        else "AI Explanation",
        unsafe_allow_html=True,
    )

    if explanation:
        st.markdown(
            f'<div style="'
            f"background:#f8fafc;border-left:4px solid #3b82f6;"
            f"padding:16px;border-radius:4px;margin-bottom:8px;"
            f'">'
            f"{explanation}"
            f"</div>",
            unsafe_allow_html=True,
        )
    else:
        st.info(
            "AI explanation unavailable. "
            "The prediction and key factors above remain valid."
        )
