"""Recommendation card list component."""

from __future__ import annotations

import streamlit as st


_CATEGORY_ICONS: dict[str, str] = {
    "photo": "[ Photo ]",
    "description": "[ Description ]",
    "health": "[ Health ]",
    "listing_details": "[ Listing ]",
}


def render_recommendations(phase2: dict | None) -> None:
    """Render actionable recommendations from Phase 2.

    Parameters
    ----------
    phase2 : dict or None
        The phase2 response dict. If None or recommendations is empty,
        renders a fallback message.
    """
    recs = []
    if phase2 is not None:
        recs = phase2.get("recommendations", [])

    st.markdown(
        'Recommendations <span class="ai-badge">Generated by AI</span>'
        if recs
        else "Recommendations",
        unsafe_allow_html=True,
    )

    if not recs:
        st.info("No specific recommendations available for this listing.")
        return

    for i, rec in enumerate(recs):
        category = rec.get("category", "listing_details")
        tag = _CATEGORY_ICONS.get(category, f"[ {category} ]")
        priority = rec.get("priority", i + 1)
        feature = rec.get("feature", "")
        current = rec.get("current_value", "")
        suggested = rec.get("suggested_value", "")
        impact = rec.get("expected_impact", "")

        with st.container():
            st.markdown(
                f"**{priority}. {feature}** &nbsp; `{tag}`"
            )
            col1, col2 = st.columns(2)
            with col1:
                st.markdown(f"**Current:** {current}")
            with col2:
                st.markdown(f"**Suggested:** {suggested}")
            if impact:
                st.caption(f"Expected impact: {impact}")
            if i < len(recs) - 1:
                st.markdown("---")
