"""
Unit tests: API schema validation.

``TestAdoptionSpeedClassEnum``, ``TestPetProfileRequest``, and
``TestTranslateRequest`` exercise the frontend-facing request schemas and
need no LLM call, so they run in the default (non-llm) test suite.

``TestAdoptionReportFromE2EOutputs`` loads the ``final_response`` section
of each e2e output JSON in ``tests/e2e_tests/outputs/`` -- a full
``AdoptionReport`` produced by a real graph run -- and asserts it
round-trips cleanly through the ``ReportStatusResponse`` API schema. This
class requires fixtures generated by a real LLM run (see
``tests/e2e_tests/run_e2e.py``), so it is marked ``@pytest.mark.llm`` and
excluded from the default suite. Regenerate the fixtures with a valid
OPENAI_API_KEY before running ``pytest tests/e2e_tests -m llm``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from adoption_accelerator.agents.contracts import AdoptionReport
from app.api.schemas.enums import AdoptionSpeedClass
from app.api.schemas.requests import PetProfileRequest
from app.api.schemas.responses import ReportStatusResponse
from app.api.services.prediction_service import translate_request

OUTPUTS_DIR = Path(__file__).parent / "outputs"

SCENARIO_FILES = [
    "typical_dog_with_description.json",
    "typical_cat_no_description.json",
    "fully_documented_pet.json",
    "minimal_input.json",
    "high_fee_unvaccinated.json",
    "young_puppy_healthy.json",
    "senior_cat_health_issues.json",
    "multiple_pets_listing.json",
    "whitespace_only_description.json",
    "very_long_description.json",
]


def _load_final_response(scenario_file: str) -> dict:
    """Load the ``final_response`` section of an e2e output JSON.

    This is the JSON-serialized ``AdoptionReport`` (``report.model_dump(
    mode="json")``) written by ``tests/e2e_tests/runner.py``.
    """
    path = OUTPUTS_DIR / scenario_file
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data["final_response"]


def _load_report(scenario_file: str) -> AdoptionReport:
    return AdoptionReport.model_validate(_load_final_response(scenario_file))


# ---------------------------------------------------------------------------
# AdoptionSpeedClass enum tests
# ---------------------------------------------------------------------------


class TestAdoptionSpeedClassEnum:
    def test_all_classes_have_labels(self):
        for cls in AdoptionSpeedClass:
            assert isinstance(cls.label, str)
            assert len(cls.label) > 0

    def test_labels_match_pipeline_class_labels(self):
        from adoption_accelerator.inference.pipeline import CLASS_LABELS

        for cls in AdoptionSpeedClass:
            assert cls.label == CLASS_LABELS[cls.value]

    def test_class_values(self):
        assert AdoptionSpeedClass.SAME_DAY == 0
        assert AdoptionSpeedClass.WITHIN_1_WEEK == 1
        assert AdoptionSpeedClass.WITHIN_1_MONTH == 2
        assert AdoptionSpeedClass.WITHIN_1_TO_3_MONTHS == 3
        assert AdoptionSpeedClass.NOT_ADOPTED == 4


# ---------------------------------------------------------------------------
# PetProfileRequest validation tests
# ---------------------------------------------------------------------------


class TestPetProfileRequest:
    def _base_request(self) -> dict:
        return {
            "pet_type": "Dog",
            "name": "Buddy",
            "age_months": 3,
            "gender": "Male",
            "breed1": 265,
            "maturity_size": 2,
            "fur_length": 2,
            "vaccinated": "Yes",
            "dewormed": "Yes",
            "sterilized": "No",
            "health": "Healthy",
        }

    def test_valid_dog_request(self):
        req = PetProfileRequest(**self._base_request())
        assert req.pet_type == "Dog"
        assert req.age_months == 3

    def test_valid_cat_request(self):
        data = self._base_request()
        data["pet_type"] = "Cat"
        req = PetProfileRequest(**data)
        assert req.pet_type == "Cat"

    def test_defaults(self):
        req = PetProfileRequest(**self._base_request())
        assert req.breed2 == 0
        assert req.color1 == 0
        assert req.color2 == 0
        assert req.color3 == 0
        assert req.fee == 0.0
        assert req.quantity == 1
        assert req.state == 0
        assert req.video_amt == 0
        assert req.description == ""

    def test_invalid_pet_type(self):
        with pytest.raises(Exception):
            PetProfileRequest(**{**self._base_request(), "pet_type": "Fish"})

    def test_invalid_vaccinated(self):
        with pytest.raises(Exception):
            PetProfileRequest(**{**self._base_request(), "vaccinated": "Maybe"})

    def test_age_out_of_range(self):
        with pytest.raises(Exception):
            PetProfileRequest(**{**self._base_request(), "age_months": 300})

    def test_negative_fee(self):
        with pytest.raises(Exception):
            PetProfileRequest(**{**self._base_request(), "fee": -10.0})


# ---------------------------------------------------------------------------
# translate_request tests
# ---------------------------------------------------------------------------


class TestTranslateRequest:
    def _make_pet(self, **overrides) -> PetProfileRequest:
        base = {
            "pet_type": "Dog",
            "age_months": 3,
            "gender": "Male",
            "breed1": 265,
            "maturity_size": 2,
            "fur_length": 2,
            "vaccinated": "Yes",
            "dewormed": "No",
            "sterilized": "Not Sure",
            "health": "Healthy",
        }
        base.update(overrides)
        return PetProfileRequest(**base)

    def test_dog_maps_to_1(self):
        req = translate_request(self._make_pet(pet_type="Dog"))
        assert req.tabular.type == 1

    def test_cat_maps_to_2(self):
        req = translate_request(self._make_pet(pet_type="Cat"))
        assert req.tabular.type == 2

    def test_gender_mapping(self):
        assert translate_request(self._make_pet(gender="Male")).tabular.gender == 1
        assert translate_request(self._make_pet(gender="Female")).tabular.gender == 2
        assert translate_request(self._make_pet(gender="Mixed")).tabular.gender == 3

    def test_tristate_mapping(self):
        req_yes = translate_request(self._make_pet(vaccinated="Yes"))
        req_no = translate_request(self._make_pet(vaccinated="No"))
        req_ns = translate_request(self._make_pet(vaccinated="Not Sure"))
        assert req_yes.tabular.vaccinated == 1
        assert req_no.tabular.vaccinated == 2
        assert req_ns.tabular.vaccinated == 3

    def test_health_mapping(self):
        assert translate_request(self._make_pet(health="Healthy")).tabular.health == 1
        assert translate_request(self._make_pet(health="Minor Injury")).tabular.health == 2
        assert translate_request(self._make_pet(health="Serious Injury")).tabular.health == 3

    def test_description_passed_through(self):
        req = translate_request(self._make_pet(description="A lovely dog."))
        assert req.description == "A lovely dog."

    def test_zero_breed2_becomes_none(self):
        req = translate_request(self._make_pet(breed2=0))
        assert req.tabular.breed2 is None

    def test_nonzero_breed2_preserved(self):
        req = translate_request(self._make_pet(breed2=264))
        assert req.tabular.breed2 == 264

    def test_empty_name_becomes_none(self):
        req = translate_request(self._make_pet(name=""))
        assert req.tabular.name is None

    def test_nonempty_name_preserved(self):
        req = translate_request(self._make_pet(name="Buddy"))
        assert req.tabular.name == "Buddy"

    def test_labels_resolve_breed_color_and_state_names(self):
        req = translate_request(
            self._make_pet(breed1=265, color1=1, state=41326)
        )
        assert req.labels is not None
        assert req.labels.breed == "Domestic Medium Hair"
        assert req.labels.colors == ["Black"]
        assert req.labels.state == "Selangor"

    def test_labels_omit_unspecified_ids(self):
        req = translate_request(
            self._make_pet(color1=1, color2=0, color3=0, state=0)
        )
        assert req.labels.state is None
        assert req.labels.colors == ["Black"]

    def test_two_breeds_join_with_a_slash(self):
        req = translate_request(self._make_pet(breed1=265, breed2=307))
        assert req.labels.breed == "Domestic Medium Hair / Mixed Breed"

    def test_repeated_breed_is_not_duplicated(self):
        req = translate_request(self._make_pet(breed1=307, breed2=307))
        assert req.labels.breed == "Mixed Breed"

    def test_labels_reach_the_synthesizer_pet_facts_block(self):
        # Only type compatibility linked translate_request's labels to the
        # synthesizer before this test existed. Pin that the resolved
        # breed/color names actually flow into the PET FACTS block the
        # writer prompt is built from, not just that the types line up.
        from adoption_accelerator.agents.listing_facts import build_listing_facts

        req = translate_request(
            self._make_pet(breed1=265, color1=1, state=41326)
        )
        facts = build_listing_facts(req.tabular, req.labels)
        block = facts.as_prompt_block()
        assert facts.colors == "Black"
        assert facts.breed == "Domestic Medium Hair"
        assert "colors: Black" in block
        assert "breed: Domestic Medium Hair" in block


# ---------------------------------------------------------------------------
# AdoptionReport / ReportStatusResponse tests against real e2e outputs.
#
# These require fixtures produced by a real graph run (data_analyst,
# visual_analyst, recommendation_agent, and synthesizer all call an LLM),
# so the whole class is excluded from the default (non-llm) test suite.
# ---------------------------------------------------------------------------


class TestAdoptionReportFromE2EOutputs:
    pytestmark = pytest.mark.llm

    @pytest.mark.parametrize("scenario_file", SCENARIO_FILES)
    def test_report_is_valid_adoption_report(self, scenario_file: str):
        report = _load_report(scenario_file)
        assert isinstance(report, AdoptionReport)

    @pytest.mark.parametrize("scenario_file", SCENARIO_FILES)
    def test_predicted_class_in_valid_range(self, scenario_file: str):
        report = _load_final_response(scenario_file)
        assert report["prediction"]["predicted_class"] in range(5)

    @pytest.mark.parametrize("scenario_file", SCENARIO_FILES)
    def test_probabilities_sum_to_one(self, scenario_file: str):
        report = _load_final_response(scenario_file)
        total = sum(report["prediction"]["probabilities"].values())
        assert abs(total - 1.0) < 1e-3

    @pytest.mark.parametrize("scenario_file", SCENARIO_FILES)
    def test_narrative_is_present(self, scenario_file: str):
        report = _load_final_response(scenario_file)
        assert report["narrative"]

    @pytest.mark.parametrize("scenario_file", SCENARIO_FILES)
    def test_session_id_is_present(self, scenario_file: str):
        report = _load_final_response(scenario_file)
        assert report["metadata"]["session_id"]

    @pytest.mark.parametrize("scenario_file", SCENARIO_FILES)
    def test_recommendations_match_validated_recommendation_shape(self, scenario_file: str):
        report = _load_final_response(scenario_file)
        recommendations = report.get("recommendations")
        if not recommendations:
            pytest.skip("no recommendation evidence in this scenario's output")
        for rec in recommendations["recommendations"]:
            impact = rec["measured_impact"]
            assert impact["class_before"] in range(5)
            assert impact["class_after"] in range(5)
            assert isinstance(impact["probability_shift"], dict)

    @pytest.mark.parametrize("scenario_file", SCENARIO_FILES)
    def test_report_roundtrips_through_report_status_response(self, scenario_file: str):
        """AdoptionReport must serialize cleanly inside the API's
        ReportStatusResponse wrapper (the same shape POST /predict and its
        status poll return)."""
        report = _load_report(scenario_file)
        status = ReportStatusResponse(
            session_id=report.metadata.session_id,
            status="done",
            report=report,
            error=None,
        )
        json_str = status.model_dump_json()
        assert len(json_str) > 0
        reparsed = ReportStatusResponse.model_validate_json(json_str)
        assert reparsed.session_id == status.session_id
        assert reparsed.report.prediction.predicted_class == report.prediction.predicted_class

    def test_all_scenarios_produce_a_valid_report(self):
        passed: list[str] = []
        failed: list[tuple[str, str]] = []

        for scenario_file in SCENARIO_FILES:
            try:
                report = _load_report(scenario_file)
                assert report.prediction.predicted_class in range(5)
                assert report.narrative
                assert report.metadata.session_id
                passed.append(scenario_file)
            except Exception as exc:
                failed.append((scenario_file, str(exc)))

        assert len(failed) == 0, (
            f"Validation gate FAILED for {len(failed)}/{len(SCENARIO_FILES)} scenarios:\n"
            + "\n".join(f"  {name}: {err}" for name, err in failed)
        )
        assert len(passed) == len(SCENARIO_FILES)
