/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return the current health status of the ML model and agent graph.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Info
         * @description Return detailed model metadata.
         */
        get: operations["model_info_health_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict
         * @description Create a prediction job and run the Evidence Board graph in the
         *     background.
         *
         *     Returns 202 Accepted with the session_id and a "running" status. The
         *     client should poll GET /predict/{session_id}/status for the report.
         *
         *     Accepts both ``application/json`` and ``multipart/form-data``.
         */
        post: operations["predict_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prediction Status
         * @description Poll the current status of a prediction job.
         *
         *     Returns the job state from the in-memory store:
         *     - ``running``: the graph is still executing.
         *     - ``done``: the AdoptionReport is available.
         *     - ``error``: an error occurred during processing.
         */
        get: operations["get_prediction_status_predict__session_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore/distributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Distributions
         * @description Return precomputed histogram/bar data for the requested feature.
         */
        get: operations["get_distributions_explore_distributions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Features
         * @description Return the list of features available for distribution exploration.
         */
        get: operations["get_available_features_explore_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Performance
         * @description Return confusion matrix, per-class metrics, and global feature importance.
         */
        get: operations["get_performance_explore_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Adoption Patterns
         * @description Return precomputed adoption pattern data.
         */
        get: operations["get_adoption_patterns_explore_patterns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recent Predictions
         * @description Return recent predictions from the in-memory job store.
         */
        get: operations["get_recent_predictions_predictions_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdoptionReport
         * @description Final structured output of the agent graph.
         */
        AdoptionReport: {
            prediction: components["schemas"]["PredictionEvidence"];
            visual?: components["schemas"]["VisualEvidence"] | null;
            recommendations?: components["schemas"]["RecommendationEvidence"] | null;
            /**
             * Narrative
             * @default
             */
            narrative: string;
            /** Optimized Description */
            optimized_description?: string | null;
            /**
             * Headline
             * @default
             */
            headline: string;
            metadata: components["schemas"]["ReportMetadata"];
        };
        /** BreedOption */
        BreedOption: {
            /** Id */
            id: number;
            /** Type */
            type: number;
            /** Name */
            name: string;
        };
        /**
         * DistributionEntry
         * @description Histogram/bar data for a single feature.
         */
        DistributionEntry: {
            /** Feature */
            feature: string;
            /** Display Name */
            display_name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "numeric" | "categorical";
            /** Bins */
            bins?: number[] | null;
            /** Categories */
            categories?: string[] | null;
            /** Counts */
            counts: number[];
            /** By Class */
            by_class: {
                [key: string]: number[];
            };
        };
        /**
         * DistributionsResponse
         * @description Response for GET /explore/distributions.
         */
        DistributionsResponse: {
            /** Feature */
            feature: string;
            data: components["schemas"]["DistributionEntry"];
            /** Class Labels */
            class_labels: {
                [key: string]: string;
            };
        };
        /** FactorInsight */
        FactorInsight: {
            /** Feature */
            feature: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Value
             * @default
             */
            value: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "positive" | "negative";
            /** Shap Magnitude */
            shap_magnitude: number;
            /** Modality */
            modality: string;
            /**
             * Reading
             * @default
             */
            reading: string;
        };
        /**
         * GlobalFeatureImportance
         * @description A single entry in global feature importance ranking.
         */
        GlobalFeatureImportance: {
            /** Rank */
            rank: number;
            /** Feature */
            feature: string;
            /** Display Name */
            display_name: string;
            /** Mean Abs Shap */
            mean_abs_shap: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response for GET /health.
         */
        HealthResponse: {
            /**
             * Model Status
             * @enum {string}
             */
            model_status: "healthy" | "degraded" | "offline";
            /** Model Version */
            model_version: string;
            /** Model Type */
            model_type: string;
            /** Feature Count */
            feature_count: number;
            /**
             * Agent Status
             * @enum {string}
             */
            agent_status: "connected" | "degraded" | "offline";
        };
        /** IdLabel */
        IdLabel: {
            /** Id */
            id: number;
            /** Label */
            label: string;
        };
        /** LabeledOption */
        LabeledOption: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** MeasuredImpact */
        MeasuredImpact: {
            /** Class Before */
            class_before: number;
            /** Class After */
            class_after: number;
            /** Probability Shift */
            probability_shift: {
                [key: string]: number;
            };
            /** Expected Speedup */
            expected_speedup: string;
        };
        /**
         * MetaResponse
         * @description Response for GET /meta: labels and categorical reference options.
         */
        MetaResponse: {
            /** Model Version */
            model_version: string;
            /** Modality Breakdown */
            modality_breakdown: {
                [key: string]: number;
            };
            /** Adoption Speed Classes */
            adoption_speed_classes: components["schemas"]["SpeedClassEntry"][];
            /** Breeds */
            breeds: components["schemas"]["BreedOption"][];
            /** Colors */
            colors: components["schemas"]["LabeledOption"][];
            /** States */
            states: components["schemas"]["LabeledOption"][];
            /** Maturity Sizes */
            maturity_sizes: components["schemas"]["IdLabel"][];
            /** Fur Lengths */
            fur_lengths: components["schemas"]["IdLabel"][];
        };
        /**
         * ModelInfoResponse
         * @description Detailed model metadata for GET /health/model.
         */
        ModelInfoResponse: {
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Model Family */
            model_family: string;
            /** Base Models */
            base_models: string[];
            /** Feature Count */
            feature_count: number;
            /** Training Qwk */
            training_qwk: number;
            /** Modality Breakdown */
            modality_breakdown: {
                [key: string]: number;
            };
        };
        /** NodeError */
        NodeError: {
            /** Node */
            node: string;
            /** Error Type */
            error_type: string;
            /** Message */
            message: string;
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
            /**
             * Recoverable
             * @default true
             */
            recoverable: boolean;
        };
        /**
         * PerClassMetric
         * @description Per-class precision/recall/F1 entry.
         */
        PerClassMetric: {
            /** Class Id */
            class_id: number;
            /** Label */
            label: string;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** F1 */
            f1: number;
            /** Support */
            support: number;
        };
        /**
         * PerformanceResponse
         * @description Response for GET /explore/performance.
         */
        PerformanceResponse: {
            /** Confusion Matrix */
            confusion_matrix: number[][];
            /** Class Labels */
            class_labels: string[];
            /** Per Class Metrics */
            per_class_metrics: components["schemas"]["PerClassMetric"][];
            /** Aggregate Metrics */
            aggregate_metrics: {
                [key: string]: number;
            };
            /** Global Importance */
            global_importance: components["schemas"]["GlobalFeatureImportance"][];
        };
        /** PhotoAssessment */
        PhotoAssessment: {
            /** Image Index */
            image_index: number;
            quality: components["schemas"]["PhotoQuality"];
            content: components["schemas"]["PhotoContent"];
            /** Appeal Score */
            appeal_score: number;
            /** Improvement Suggestions */
            improvement_suggestions?: string[];
        };
        /** PhotoContent */
        PhotoContent: {
            /** Pet Visible */
            pet_visible: boolean;
            /**
             * Expression
             * @default
             */
            expression: string;
            /**
             * Setting
             * @default
             */
            setting: string;
            /** Distinctive Traits */
            distinctive_traits?: string[];
        };
        /** PhotoQuality */
        PhotoQuality: {
            /** Sharpness */
            sharpness: number;
            /** Lighting */
            lighting: number;
            /** Framing */
            framing: number;
            /** Background */
            background: number;
            /** Issues */
            issues?: string[];
        };
        /** PredictionEvidence */
        PredictionEvidence: {
            /** Source */
            source: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Generated By */
            generated_by: string;
            /** Notes */
            notes?: string[];
            /** Predicted Class */
            predicted_class: number;
            /** Prediction Label */
            prediction_label: string;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Class Confidence */
            class_confidence: number;
            /** Modality Contributions */
            modality_contributions: {
                [key: string]: number;
            };
            /** Modality Available */
            modality_available: {
                [key: string]: boolean;
            };
            /** Key Drivers */
            key_drivers?: components["schemas"]["FactorInsight"][];
            /**
             * Uncertainty Reading
             * @default
             */
            uncertainty_reading: string;
        };
        /**
         * RecentPredictionEntry
         * @description A single entry in the recent predictions log.
         */
        RecentPredictionEntry: {
            /** Session Id */
            session_id: string;
            /** Timestamp */
            timestamp: string;
            /** Pet Type */
            pet_type: string;
            /** Prediction */
            prediction: number;
            /** Prediction Label */
            prediction_label: string;
            /** Confidence */
            confidence: number;
            /** Response Time Ms */
            response_time_ms: number;
            /** Status */
            status: string;
        };
        /**
         * RecentPredictionsResponse
         * @description Response for GET /predictions/recent.
         */
        RecentPredictionsResponse: {
            /** Predictions */
            predictions: components["schemas"]["RecentPredictionEntry"][];
            /** Total Today */
            total_today: number;
        };
        /** RecommendationEvidence */
        RecommendationEvidence: {
            /** Source */
            source: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Generated By */
            generated_by: string;
            /** Notes */
            notes?: string[];
            /** Recommendations */
            recommendations?: components["schemas"]["ValidatedRecommendation"][];
            /** Rejected Hypotheses */
            rejected_hypotheses?: string[];
            /**
             * Iterations Used
             * @default 0
             */
            iterations_used: number;
        };
        /** ReportMetadata */
        ReportMetadata: {
            /** Session Id */
            session_id: string;
            /**
             * Ml Model Version
             * @default tuned_v1
             */
            ml_model_version: string;
            /** Llm Models */
            llm_models?: {
                [key: string]: string;
            };
            /** Timing Ms */
            timing_ms?: {
                [key: string]: number;
            };
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /** Errors */
            errors?: components["schemas"]["NodeError"][];
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
        };
        /**
         * ReportStatusResponse
         * @description Status/result wrapper returned by POST /predict and its status poll.
         */
        ReportStatusResponse: {
            /** Session Id */
            session_id: string;
            /** Status */
            status: string;
            report?: components["schemas"]["AdoptionReport"] | null;
            /** Error */
            error?: string | null;
        };
        /** SpeedClassEntry */
        SpeedClassEntry: {
            /** Index */
            index: number;
            /** Label */
            label: string;
        };
        /** ValidatedRecommendation */
        ValidatedRecommendation: {
            /** Action */
            action: string;
            /** Feature */
            feature: string;
            /** Current Value */
            current_value: string;
            /** Suggested Value */
            suggested_value: string;
            measured_impact: components["schemas"]["MeasuredImpact"];
            /**
             * Priority
             * @default 1
             */
            priority: number;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisualEvidence */
        VisualEvidence: {
            /** Source */
            source: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Generated By */
            generated_by: string;
            /** Notes */
            notes?: string[];
            /** Photos */
            photos?: components["schemas"]["PhotoAssessment"][];
            /** Overall Visual Appeal */
            overall_visual_appeal: number;
            /** Best Photo Index */
            best_photo_index?: number | null;
            /** Observed Traits */
            observed_traits?: string[];
            /** Consistency Flags */
            consistency_flags?: string[];
            /**
             * Photo Strategy Summary
             * @default
             */
            photo_strategy_summary: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    model_info_health_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoResponse"];
                };
            };
        };
    };
    predict_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_prediction_status_predict__session_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_distributions_explore_distributions_get: {
        parameters: {
            query: {
                /** @description Feature name to get distribution for */
                feature: string;
                /** @description Include per-class breakdown */
                color_by_class?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_available_features_explore_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_performance_explore_performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponse"];
                };
            };
        };
    };
    get_adoption_patterns_explore_patterns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_recent_predictions_predictions_recent_get: {
        parameters: {
            query?: {
                /** @description Max entries to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentPredictionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
}
