"""Adoption Accelerator — Streamlit entry point.

Run with:
    streamlit run app/streamlit/app.py
"""

from __future__ import annotations

import base64
import os
import sys

# Ensure app/streamlit/ is on the path so pages and components can be imported.
_here = os.path.dirname(os.path.abspath(__file__))
if _here not in sys.path:
    sys.path.insert(0, _here)

import streamlit as st

from components.sidebar import render_sidebar_info

st.set_page_config(
    page_title="Adoption Accelerator",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Header image
# ---------------------------------------------------------------------------
_HEADER_PATH = os.path.join(_here, "assets", "header.png")
if os.path.exists(_HEADER_PATH):
    with open(_HEADER_PATH, "rb") as _f:
        _header_b64 = base64.b64encode(_f.read()).decode()
    st.markdown(
        f"""
        <div style="width:100%;margin-bottom:16px;">
            <img src="data:image/png;base64,{_header_b64}"
                 style="width:100%;height:auto;display:block;border-radius:8px;"
                 alt="Adoption Accelerator">
        </div>
        """,
        unsafe_allow_html=True,
    )

# ---------------------------------------------------------------------------
# Global CSS: color system from frontend_design.md Section 8.4
# ---------------------------------------------------------------------------
st.markdown(
    """
    <style>
    /* --- Base palette --- */
    .stApp {
        background-color: #f8fafc;
        color: #1e293b;
    }

    /* --- Cards & containers --- */
    div[data-testid="stExpander"],
    div[data-testid="stVerticalBlock"] > div[data-testid="stHorizontalBlock"] {
        background-color: #ffffff;
    }

    /* --- Primary accent on buttons --- */
    .stButton > button[kind="primary"],
    button[data-testid="stFormSubmitButton"] {
        background-color: #3b82f6;
        border-color: #3b82f6;
    }
    .stButton > button[kind="primary"]:hover {
        background-color: #2563eb;
        border-color: #2563eb;
    }

    /* --- Sidebar --- */
    section[data-testid="stSidebar"] {
        background-color: #ffffff;
        border-right: 1px solid #e2e8f0;
    }

    /* --- Horizontal dividers --- */
    hr {
        border-color: #e2e8f0;
    }

    /* --- Subheader styling --- */
    .stMarkdown h3, .stMarkdown h2 {
        color: #1e293b;
    }

    /* --- Caption / secondary text --- */
    .stCaption, div[data-testid="stCaptionContainer"] {
        color: #64748b;
    }

    /* --- "Generated by AI" badge --- */
    .ai-badge {
        display: inline-block;
        background: #3b82f6;
        color: white;
        font-size: 0.7em;
        font-weight: 600;
        padding: 2px 8px;
        border-radius: 4px;
        letter-spacing: 0.03em;
        vertical-align: middle;
        margin-left: 4px;
    }

    /* --- Spacing rhythm (8px base) --- */
    div[data-testid="stVerticalBlock"] > div {
        padding-bottom: 0px;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.markdown("## Adoption Accelerator")
    st.caption("PetFinder Adoption Speed Predictor")

predict_page = st.Page("pages/predict.py", title="Predict", default=True)
explore_page = st.Page("pages/explore.py", title="Explore Data")
status_page  = st.Page("pages/status.py",  title="System Status")

pg = st.navigation([predict_page, explore_page, status_page])

render_sidebar_info()

pg.run()
